spring.application.name=demo
spring.datasource.url=jdbc:mysql://db5020419523.hosting-data.io:3306/dbs19656994?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=dbu4122806
spring.datasource.password=Ilovemygirlfriend22@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.platform=org.hibernate.dialect.MariaDBDialect