name: Build and deploy to IONOS VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x springbootserver/demo/gradlew

      - name: Build with Gradle
        run: cd springbootserver/demo && ./gradlew build -x test

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      -  name: Debug SSH key
         run: |
          head -1 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no springbootserver/demo/build/libs/demo-0.0.1-SNAPSHOT.jar ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/app/

      - name: Restart Spring Boot
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "pkill -f 'demo-0.0.1-SNAPSHOT.jar' || true && nohup java -jar /home/app/demo-0.0.1-SNAPSHOT.jar --spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }} --spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }} --spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }} > /home/app/app.log 2>&1 &"